### ISSUE TITLE
Japanese Wikipedia dump link has changed

### ISSUE THREAD

**Issue by HelloRusk** [rinnakk/japanese-pretrained-models#5]
First of all, thanks for great project!

Currently, wikipedia link is fixed to `https://dumps.wikimedia.org/other/cirrussearch/20210329/jawiki-20210329-cirrussearch-content.json.gz`. However, it looks like the manager dispose the dump as it becomes older. The latest version is `https://dumps.wikimedia.org/other/cirrussearch/20211025/jawiki-20211025-cirrussearch-content.json.gz`. It would be grateful to note it in README.

(I also find that CC-100 link is broken now, but it is not your fault.)

**Comment by ZHAOTING** [comment]
@HelloRusk Thank you very much for noticing the invalid links. It has been now fixed by the latest commit.
Let me close this issue.
