### ISSUE TITLE
Please add "tokenizer_class" in "config.json"

### ISSUE THREAD

**Issue by shirayu** [rinnakk/japanese-pretrained-models#7]
Please add ``tokenizer_class`` in ``config.json`` like
```txt
  "tokenizer_class": "T5Tokenizer",
```
.
This enables use of ``AutoTokenizer`` like
```python
tokenizer = AutoTokenizer.from_pretrained("rinna/japanese-gpt-1b")
```
instead of 
```python
tokenizer = T5Tokenizer.from_pretrained("rinna/japanese-gpt-1b")
```

(Other models can be changed in the same way.)

Related to: https://github.com/cl-tohoku/bert-japanese/issues/24

**Comment by ZHAOTING** [comment]
Thank you. It is now solved in [this commit](https://github.com/rinnakk/japanese-pretrained-models/commit/2926c14bd12afa754ee4fff4cdf8c2e425895091).
